# Site settings
title: Bernhard Rieder
description: >- # this means to ignore newlines until "baseurl:"
  Hi there, my name is <b>Bernhard Rieder</b>. I'm an Austrian game developer currently employed at Ubisoft Bucharest.<br>
  If you are interested in working with me or anything similar, then feel free to get in touch with me via any social network or e-mail. 
  
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://bernhardrieder.dev" # the base hostname & protocol for your site, e.g. http://example.com
# repository: bernhardrieder


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Bernhard Rieder
  image    : "/assets/img/me_face.jpg"
  email    : contact@bernhardrieder.dev
  github   : bernhardrieder
  twitter  : bernhard_rieder
  linkedin : bernhard-rieder
  facebook : rieder.bernhard


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name
  portfolio:
    output: true
    permalink: /portfolio/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"

# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock

timezone: Europe/Vienna